directories:
  output: portable-build
  buildResources: build
appId: com.frpc.manager
productName: FRPClient Manager
files:
  - filter:
      - dist/**/*
      - node_modules/**/*
      - '!node_modules/*/{CHANGELOG.md,README.md,README,readme.md,readme}'
      - '!node_modules/*/{test,__tests__,tests,powered-test,example,examples}'
      - '!node_modules/*.d.ts'
      - '!node_modules/.bin'
      - '!**/*.{iml,o,hprof,orig,pyc,pyo,rbc,swp,csproj,sln,xproj}'
      - '!.editorconfig'
      - '!**/._*'
      - '!**/{.DS_Store,.git,.hg,.svn,CVS,RCS,SCCS,.gitignore,.gitattributes}'
      - '!**/{__pycache__,thumbs.db,.flowconfig,.idea,.vs,.nyc_output}'
      - '!**/{appveyor.yml,.travis.yml,circle.yml}'
      - '!**/{npm-debug.log,yarn.lock,.yarn-integrity,.yarn-metadata.json}'
extraResources:
  - from: frp
    to: frp
win:
  target:
    - target: portable
      arch:
        - x64
    - target: nsis
      arch:
        - x64
    - target: dir
      arch:
        - x64
  icon: assets/icon.ico
portable:
  artifactName: FRPClient Manager-${version}-portable.exe
  unpackDirName: frpc-manager
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  artifactName: FRPClient Manager-${version}-setup.exe
electronVersion: 27.3.11
